name: my_cli_tool
description: A sample command-line application.
version: 1.0.0
repository: https://github.com/kenresoft/my_cli_tool

environment:
  sdk: ^3.4.1

# Add regular dependencies here.
dependencies:
  path: ^1.8.0
  args: ^2.5.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0

executables:
  my_cli_tool: my_cli_tool
